language: java
jdk:
- oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.idris94@gmail.com
  password:
    secure: Jt4Uf6njmI+Zr7ZDl/q270wa2ol4D6Rd3iPd7ut7QjBL7Alylw5j8jPkP30jOaGadZtMO8n4QGbHH9AblLjFnEOXCDPbLXUYEYnYoQ1IP4F2r16oRdlhDQv4Z2FESrnyGNL3EVTuCdEuK8Zuf9ah+WF0pgvUFxMGLG8hQV5Vs+giLSFExhXVSoaRWoUN1FJ5JGa94084x2lmiyuOgHLHyLNOCCgmJzHdDjxS68hkITBYVSt6/qWvE6m3nFjAfs3L+aCBZT0YGVEBOMYb3HHQPqPHEBw3Z6fcO3V54+DdWPfw0+jQDtz39UC4zforxRPR171ayfW9K8ccgVWckoNEZ6oMvfqR4oOsdv5Wdf7aGmWh94jJ3i9L/gHQgDGQDZgphWd2r2IZvaffiFsOlx0vmZ/Zk0yO/+DOkNgUWC40pcKZwUffDK8F+wYfzEl9YjkdtqrK2yAveWEbltUfXsIaLcGXXTGw2GfcYTMHoKBA5ivxkcpOf7VlGrsJ/8K2qSL311/41EiZHlnsykqy8xIVhZ4Svi8J0o82wNO76OfMt72p0wgCa9Ax0gysCFCuxcua/3vSYXkMyZdZaJbq7UYg02lFkvdbHxNy6UPo0Rrb+GM71fvaYZAJG6LpjA+82os8996W4w2vmmMWIAI2/Y9y+uDGUOXOJuPZqquLsoMo0Cg=
  organization: charon
  space: julekalender
  on:
    repo: DanielIdris/Julekalender-webservice
