language: java
jdk:
- oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.idris94@gmail.com
  password:
    secure: I8xdkSBJbvkOnCibU8CdNhNQA9fcFSpx/hqjLB+GDOVQGxgt3Bhd8B34CSUWRRZlejFbSyOFQtYkbf3ROKVRcAH1RffcnnWW/U/kY4lm2mW6iR2yO4IbnpDR0g5iA2r8IEG7timssrDZUUmWmHu4aVZbuWmbrM+Qln+1x8YHRQevT3gzS1EzpVDONh8OPU0KsvRyfkvYhhmG8wpro//tkD+jjflpTGk1C1DKo47d2eVJskPZ4X5wE/nJNg+dXSSIVzwu41P+kNnSQG9eM1gfV9Wtdzj2VHVRmVGT2RjNOt5tSkMQQm6zFApwpI3/PqrQAb69EkT22u7D9QZU9SG4zouMjNBkyy62vkmkxohrXaZ60aANYsZ9liAXaGLHFhXybvDo1m8BFbfWB2QUhPQtqiy3FuQrV/5b6xSQxv4QiGjnPA+bDRRCCMVgHOmyEKJCAxNGsBXh6xCDzMxhZxJeJjJ1I4pJdUK3/ceWLhPc+P5EbwfKZ4dLcrtePlZjudEKnqol/GgC44DtK7GuQGY9hm7OMzsScHcXDPCll+ecAJmNEjRSCouKvDQtf13jiTeVGUZ23cPzT5A/DoaNOKVrskkgMglWjSG44OTygIgniJu3Bzks3VUj9s59VwOCGvBFEeXw3APTo08EdZr4cXI83ABZWJtu2yn8m2H/AtdqWus=
  organization: charon
  space: julekalender-webservice
  on:
    repo: DanielIdris/Julekalender-webservice
