language: java
jdk:
- oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.idris94@gmail.com
  password:
    secure: KlQ1/Wb9hLQ+CwKZYiGm5rtJfxt7QZOjlijSgnyuJ1zO2tR5IfjRCpClLoOvM9RWed+blcEdDa46zE2gsDl/b5U3pxRQ9uU/pGzgEoBgzhy1+zXbDsScn36aspFZ0f1cmPg0NlUn/lwzFV2lL0PBvcS7ZbRmTdNRJKfPBjJyaxAaw93yjMN6gI/g94+RhfoWLUXOq5LUlNjVVP/lcTt3skEtUcZ/orzIvGLWneI0XkyK62wWU8oCQhCz4FDCEMBK3kr2OwjBTnu6jJ4hturCWvaIib5CZMurXXbKhDvznQ1IcBS91mT5FeWaIZH+lFqWU3QIEA/ev1DYjBluZ0WdQpfVQ1/+jkK59YygrAM7ishPi85X5+bb0JA/pGwYGASRg9g5E4Cgaf6TyXl3Z0pS9Xyr1XybC95rGG5VOCkQo6q577c4uiMtV9A9B/YP1vaNvw2yEujXyX8SJxp05TilmoiXxHeZJvUPlSYwiu3Q5WMIdj7UaImZBi8WPrOPmgLkHvUBja42Y8J4QVwF1T74l0HAl6yjx+pqVKcD5/wKokgtgqsNV8FbVwt4xF/OLKSxQY+oOFAQfrndyH17zpt0+bANcdRuOz21Gv/N+q3BbEX3OIX9apRgAFVx2/iixhf5DUL59BH9wV/fGPUMqApYRnDxTk2m5a5T1vnO6HcuVzY=
  organization: charon
  space: julekalender-webservice
  on:
    repo: DanielIdris/Julekalender-webservice
