language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
deploy:
- provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.idris@bouvet.no
  password:
    secure: "W9+h4gP0qaGFvIv0adNUGW/TPxKnM9vHKk9OuT7064C7yVR//5jKD5ALUU4ZgquyFuF6XWe21CVaNkscntdCNF3cNSHTi9Bcd70DR3BphFf4mcPKXKZW1vVLGS1sgen4Rvjt3iaZWPr1KeWszS7tFZYPDbqIGhxNqcPPItxAz1QOM14dkij6ApdHcM60NyDuk7uIrWuB12Iapiynh5LL9NI6ELI7MPnoAOQGLp9CvBUDIcMZNisSPgHlb/j/oXQRqCD/xsHAL2sKID9an2KsRkxs/PNvoDri5u7sEQ99ugURsOyyOMYnxdoUd3QgsIN1D7gd5Bpg51qLPaqYeA0BlXJcaHVs0GmrRdi6h3bmotSS1hhA+sHBcDs9Yr7Bl+nVvaPu6vpPczaOGqUG1Q7EPt+IbFiKv97Xy5UCKfRVVaOix600XRVYVj3xGtHB444JvLwsEkWZFrBfncotA920+vRtgKep474gkQyHxFLdyN8WGINEQrIpkiphlhu04emKvYvZIb0o1cHzaLZcF2MwuNIsn2eQhZ5ye6+qzW8vxCAnfIAjaPj4YWo6+KartGYsLjonQ3flor9Rz6kxL4n4GJzYqcS7A4sBc7fV73+iypyfbNbyY29JEfIQQuHlqWtebIv2Kgw/X+WxneV5RVexggemNLITwXJ6Ohi1Rq1s28Y="

  organization: team-hydra
  space: development
  manifest: manifest.yml
  on: 
branch: master