language: java
jdk:
- oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.idris94@gmail.com
  password:
    secure: XraJ/MKtBRk0hH5sNbQHM+U+/cycGV7UigV+V9EUPfiADFAEM/kMXA6J419Lu2srbmhgDaDAORQ/wXp4Yg38CQQx74lV1PgG5jdYqNoC1DD0lAzj/T/hFE/5RI488yMIGudruBEDBQNCax/iKzcJ46ue+CM8ke46sL68aui8k1aDWVp+VsMXrcuBCepybDRUffksIWbZ9/Qltse1Fgcyin+DXM6Bcb/tQucrrZrxCcBhNt6qWfHV77lmucUbQClOINPjBgrm2zyA/ESGi1gDXzS/UYZ+tk61SYuqh5TvL0CkWqh81D9K3CRS45Lte7My4KKwEa8j4vAx/e1lDC2jjKH2+dIjSP86Lg3OhY8AhCd91qtl6gtdtF8MVhP/oDotTw2Hl58OYyqixFDrjs+WR9d3NfqMH3hfbNYUyxz6LEqb7/amGYMoUkcL/CwuzUYtwYQJU7lVt/LWZa+OGUsGyKzuW9urnOZtcBaADnutfNA/IiBWwTrJmcGAR2MrMIbVli3Nf4icJ2sLIBTvdheFpJ0uOH1EDL2K+WHNS7yNE2O3jJoYKwFGEbFAK2SC+nl7/H0J4Ww5B3gei6opQ073I4xPobtNPmRwcBHL9/VKp1OFEV8f9rmdQCGSktNjI2WqlEsGStDqZwcPCjOVhAHc6jGzcW59RZjn+kXZ81Xw3hc=
  organization: charon
  space: julekalender-webservice
  on:
    repo: DanielIdris/Julekalender-webservice
