language: java
jdk:
- oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.idris94@gmail.com
  password:
    secure: b/FGyS5AAmCjnOjd12mJA1WPCZeCIjz49cWdj+rXs/XVzWOw8kCHG9xQv+bKPzQ0wFBbxbvmL93iBbwLy+061QpMxREfEFV/Czo2rRbzG7NMmAohh2C84RaLuBwoxf+0i1zpy43HYZf9nQyBdHyowy6W8lTwdquSZqdxycp2kexZjhITKvPW3TX47mJk6HmtqjnJYKYFQN+2q+AVNjjlLLwHWKjLPzgHoZEPWYQRuDtkTQtpPOEmMWNjejBepC3nI2VwjzbXSAsvqbJClZsNTJYoUQT6kSb/H/Yv5PFYiQORqVBz5WqH7Riu0teVv1B7axzWKIl1ufaiCeNwRo83aRMqZHoVJUNRJryfnCbEp+njUh7iENOaRlXA86w9Gj8xXUrslk3F19pc+lwfyEEm/h0EW5wjOIIX3gjVWnXF5YV29tlEm7KV+fjDu+g39ya4LexuXMib2+gAQ6m5kzLI8yoTChBp4J9XZYkqEx0hh06nvi9z3ivXpcdr2U/av4Y2/Jw1xKNoJ+vhufg8QSKqj2XOt/VKFguNu7HnGDp/dJ049nigVkFdbuLplIGmsJx0S/DMm6xctYI0lRSew7AEcWkkhosn8zJRnuNehhRX+A3sAuSvg1UPfWsC0Exa/CNKRkP/CmHneDpy76Ufj69DQhmH07D8II2J3KRNbfJAfUs=
  organization: charon
  space: julekalender-webservice
  on:
    repo: DanielIdris/Julekalender-webservice
