language: java
jdk:
- oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.idris94@gmail.com
  password:
    secure: pqjcKBgcNp90bZ+KRDaXcankmeYkqFEEf1OKbNHBUjLPhU7bzlXi8yMbQuAKNPmi/QbwJxdMhPiWvAu4uU+5tNpxRk7l/vuAifGyaGQ+bspmEq1tKlTwDNgdUSMPmbMgOu1/RJaHWLv7aUrTy2QjV7VGvk8vsOZt1oIZ1rzilNw2TX9DYWuASZZBuapED1XAboBOEqOCh6G0/0RF4uYZMEFCRZGRzv6jo1MsONXvPmsTXcgvS4B1FhA3jIgpThidpj9iBAi50P+kAlkH2Tq4hIbqserlr6P+QXxMqDURei1ifutpvdT0PZfsT6xChHVd8Mi40C6kSLEcef88vujgC3uIzBABPuZdPanGQ829zpygfW7T9D1PSMqz41FK9DIFIj5RVEII2fGq/oMGdfNmxwuKzgDGia5c5pen3EhZC13u1gOtvxjrkMBD9lQSHLrWOeLDy9H1Ys2qoHtHN7BW+GkQ3M7bjxIJBqAsNBArV+Zn0h0Nu5uaCSTw1QSxLiQ4jTNC0U/xPwPRj4O/XnBWIWeCd2bU43nBBUZYkd4G3GlZgFlKIxBA2uM8L1SbYYNeOMAwaYyI6rZ19PyOp+KdbVrQl/jKSfEA0EWYasOZDpGHQe2MZpbrmsI8TLb2anBiM8FTx4iWD7jchSYg2E2xj9vAx9iExUA4zHHJ/q2JlTY=
  organization: charon
  space: julekalender-webservice
  on:
    repo: DanielIdris/Julekalender-webservice
