language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
deploy:
- provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.idris@bouvet.no
  organization: team-hydra
  space: development
  manifest: manifest.yml
  on: 
branch: master
env:
  global:
    secure: ChsIdf30BZoCNyOBQDGW7R3zbfjaRErNoz2vQjBlhWVb1DxIVRiU/vx1AJ+RSfbPo0fQdwYhJ456dRZlSM+Stynj4f8MRZ/tCBPNBOaSBMeF4zSIcrtQUC2qyQDHvzch2EjXIHQnVAcSRNWg5E1Pe5CZIbmZNx+TYFBXSG6ZJBIG8hFhagaYsc77Y39UHr130mHK0ulMISP0IOtF2zP1qgiHKaPLYMMfGutlUQNA4gOMOs9tBBgMxPBdFXMijqsvXZ5dVGEDDlk9aEu8RO6salDdEO8iSt4eYEwed2bwkWXWpgqBnGSh1a5BhBM8Nu0mGh7ogidS342G589X/732bQq4TQUiOgSF1gZokwtm648lp74GX4PUOgq1uT0D+jaggVLidLxnV3kOYHpbW9ZCE5wRuj29FcRsjQ2eGLJ8/3A/mHyZDO1d3Agio13/lToHF4UB8dZKeMbn/lNy8ogGuIMWZ+Sly/Zpy+kXDDef1j5H2RSYEVnEDGLU4dijkrtUNqJ5eGwA1rfH+eM4BQLFgr6xmF2ykmJvMV0MkMbAZE+Td0+56NTt13tEJDAi6LXIOMMtRgLwfWOz421gqAeI8xnW55n4pgb/xBkpHiltNXUpWZDWv0SjclIM1AlVSU0ju/y2E1XUaYSEb4cOLS8yU6AM4vnHvJ1bkTYgBwDAcuY=
