language: java
jdk:
- oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.idris94@gmail.com
  password:
    secure: PmullmkZBgpgWxMjLW3uSOU5NNRg4SO2EUwckdVigpG48EzMhSzC4Mslu2U1BmGWW21QQ7kM9S/eHEddAw196p5M0fN5oXAFlU3sxGXcBirhsgLuLCyysiSaVU3gaWwfjVWCFSJM/zbxTPFHX02luij6tYiAgnWQTb1X2XiRTK+Ri/ZgasZQcIdXfBYAgrsZV8rrrFAXul/YPcqP+cZrjr0ZopD1B3mozt/o+bTGsogF4pptDcDh2ShpSRSBXZncCgcj3jgu5ab+USq6xTpCqhwa8ZNCBXim4LIiKLRQMZ4WMCMEFU9F5aciUcHCwVpF+Pw57UDRoOfu51VFx/wVZziFILBGS0I22gFGoVYBRiBNvKLD0xQLWYREGAqqxsjEyxos4ePgUr6GHBhbSB3qVMKl3EL9PMEgWN/ZeeUTBPYWJo7PIQs1ibd9sbbbFtYauAwzCTZy9u7AYU2Aw774+BCymIdLJJi2AFE5dpt7gxfeBjAGrsU80w3o72ewfrpxTb9k8QoY0UimQXawS/hjo5j70VyuJv4Bl4U3u9OeNNmgE2akDSWLiCQr/ND/XxzVewwreRQpHSZooLNH2N/zDf85cVMpMjC6fA3ePr7Q+4Ab4UVJZhe8RTiKvxYBRcC7ZFeycY80ZjTMP2nKYI01ZrN7XvvUDT4yEhRN9pYxPKI=
  organization: charon
  space: julekalender-webservice
  on:
    repo: DanielIdris/Julekalender-webservice
