language: java
jdk:
- oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.idris94@gmail.com
  password:
    secure: AcrLEBnW6l+Vccs9rbJBV0ol9Rs2MnpeaTH7Z7Pnd5cOaXN77kD6z7aSq0YqdYdXspquvyCB+MSVu8zzmU2waoYoQFMHC5uy6Hkrl/+T9aGbDDc5Ith9U1OAu5H22BHq4gLObZqPgKu0j2awd5gxJB0egpnQjop9GrzPUl8+L9Y6+zMzrM421oGpbIBl48ZbTT6YRPxJH6XINWkE8rd7PjJKrP3flFRVuKvfwIBVQUrl9UrYMSpCN0+3w2QHLSqsFSREq+/jV0xl0s4RqPkHrIq1yWZFJH2q473aWXwo6NaCP8SMGNjTbWmeZMYNk1lMOwJ8xoDO8LGURkLPliPryxiL/FzP9oIFwWSoprNardx8NZaAQkJbtBlLe/EjLOHGNItr+2iMr6Porb9BzHywr6sEroVbbRINznfOh5Z7W/6MXhFBRkoWkI6xF68pc8FYMTUqP6P2ng6K0N9xyL73ZgtvxxP+h3zG0i+mk3ysOCz5hMQNPRs1KjXKCQzvLZMdvjTB/0lKZie1UsZsQIQddGqoAQiLZp5rdl6lNHORQxFQNAEcyQdc+xAGsujcYiMGeNfonm9KvEIxlfa8CpyVSrIe7rgfILhKpTOgEJQNyz1oicuSBe/BQhBufQLTaxlr8BEKYBW1ue+LeRptApReHnPRCuR5VNRdGDhh2uOMVSg=
  organization: charon
  space: julekalender
  on:
    repo: DanielIdris/Julekalender-webservice
