language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.idris94@gmail.com
  password:
    secure: LhEkchWK4jDaueI09ZDLJCh91Ir89EenJTaKUidDZ7DhnWP9m5fOs1MvdsjAwaPH7Neus2Wf5VqOEwSP+IHKGnVbf1LHwDRFfbHL97pn5y05rld2fy2SrJUCrD6XIKMvU1opf7LUK3Yx6uT0upyOg8DwDRy6CDDev/sRnIXvRbwXmvZ2XjYJLx1bFsV/t8sUBs1rQlz8m5T0wKGSGNp3YeM+vUAeiIHhUDrk+Lm1aEutkNuXmD8YPvxIO21ZzLZ6ctTP1vdcM127FGRNMmVKEZWRnGRuC+/6KeowuiHbU+G/17MvNiN0VlaTIr7yOIZOTNcNIH9flZFZjkcfDhbU6zIwqXFa+8hIiAhL9HJoHqOIIHPWHJKACzjf6WAPW+hMEdClRKvs+lhasjyEo5sXAGz5q5O5gBt2J9amer5HEu6lM6OmHHZgfw+/Cw0ijkghCgc1a+PD+dgBqBUVrK99EkAxSwHBL95My75QyO+1yC5sTIwL72FS0gS4uGOUXf4uS22kEGimpL0gEkOFlQn5m/ehuzqDvIfQwoq2n8UIUqaTDfOLLuwBWzByNjdDkTcKcgvvO3oq7xzV8+u4lAKeR1haE64AZO8cmVvw1Q/ury4gSBCxRrfHGhiYSz6GNImXZbpASNWoaKPvqFIKIIr9b//6gAgXCrj/kLebodIFZls=
  organization: charon
  space: julekalender-webservice
  on:
    repo: DanielIdris/Julekalender
