language: java
jdk:
- oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.idris94@gmail.com
  password:
    secure: qYEZvDPnoY0O6872KODcWRjAFA/qDwKuSYqMpbCagvCxuJXHmB6NaLbeRhBVYHb+VggQkRvbJIoL2YWlGwDchFce8ni6SU9IIHCOTxF2lF/KlFsxMXIy/mh3MW44VpeLrsg7n57JnTq95hEDO60sTaFuOxKtNXVfULJB5AwV4VO9lzBzKk2sUn3kvmCUMbpAtGcxhuyeuvl7eBHjIjaggkFA6kvdxb+xbWmcM0dgiX/VDgGGgHn1GuTovenhPpsDXQNiE8qsGBFDygKjEtxmzmhoL7pukqVx1A2CthnQ5mKVKlr5GM6eWI821C7U86i4V4PGlGHmSWfZQxp/eUymd2mTGMWBlBRDtGGVxMat+fykb844VaGE5Cz8LT/VJVQxFmdcLqTn3YqXxddaIE9TRDNeNwpThpJ77iZV9bSERuIrARnsNlhBweuPXz4wdzlWZevPfiQL8jcLo3AKipW/mwNG/6JSDMiC/5/1wGx1ifG0C5i4/2ojqp+aS99ZuoX8M/9yxKyJUVWa9I9G57dqfyRwuoXiYZUSwhl581LQH8vfbOsxK3CJduX11gcRhT+ZbzBEkxBCxBH0djsp//leydsGC0cDYqeCUltGMk104PervJyg52Wo8SUueTpTTyOKxDNM2krsj9i4z7qh5CFC8O6Nv7VmMfvSgYFzLh5EPpA=
  organization: charon
  space: julekalender-webservice
  on:
    repo: DanielIdris/Julekalender-webservice
