language: java
jdk:
- oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.idris94@gmail.com
  password:
    secure: fs0g8urojVuP+Y+F5DMlNF6ccoX/I9o6n1wnHAv2gkPvCS5KUWAwYS98KJrRdihEud7ov1dAWxM8UQ6P/n8VMMiaGtaHxavy9dBf4mpWDn2bqBelwpgEDbV0+6rX1uIbkEb4qbYpsL+xVf73jtqWCMpF1zCE5ch2CW599kmt2BHg7mvyQVqTfLJxhIBfsC8UZh9wmV/RUvUrle6UBnZX0Ba0gfNSdoyGDohvsCQN2LUPSI4PzzmtnMs21jpeZTBdZgJ0BS0kDzBXaZ6NYQNllVdb2fGOf4X77tCRWZngFdpwTfhxffBpZ33Epxju4OQX3muVNZ1ffXd3Xs3HPD0P1Cn5nDJeYzjI+nEZzEcH1BTQ7tgnF8omnkmhcIyrHpM0h66mSBFCdBS3Ia0ll7shUwrOuxfGqWkvTNK8w84xYwdQBJgWnr2lF4BGvEya5s/7QvqPczLt0J01wVtyPP3QExwnc03ocO8+pVtKea5wPcUOBdgCRn0BP/kIZMUvC8rpWv7f2aZ2Mv2kOFoZ71E/ZPP1gRwYSt19sQRPm8dssklqN/IrS1CRVXR9JjXn21YH8d814yGhXfTVQtR/q04gPY+n4vmVd3dvvZYtMnMjtB+K+HjuTycxbrLP4iyw3WIBxWJBEZQJNVm1S3hGpKznvRDlMbCkq7iLtQM3R/q9G9A=
  organization: charon
  space: julekalender-webservice
  on:
    repo: DanielIdris/Julekalender-webservice
