language: java
jdk:
- oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.idris94@gmail.com
  password:
    secure: VrSFnlkd80BkVXWan/JpRlH5QW5ljAYXaIIu4org4tLLS5d9b9qjf7A8iN8HIiCcUXnO57zoycl7ZXKfRKIjr55vTY5052vEbjaitniNrElAxiCJuTWDDglHytBMnboALCvjhY4rn+bzWJQeyB4+1xrZaRa1kX4TNod5WgucyokMtqhSoh6ZX63ZbQm95jkzk8QAZDWxRn1XFKO3ZVTVFlh0E5ayLgzoyw47ql0zVTkxyUbiUHGQNAo53fpH0Sin5mZSArLkwGa4X0wBUuSSoJlVuQ+PNLsbsuX9O0mXhR9piDyWYZbLyXi/K/feRpYdGwkwE5tKoPEqfQumzTAXTZgOClUmLDYlCDcNq4p+wNcMnQq+3EfB/luV8wwqfbmWU0tbULFm4CQ8/5jhKwOKxgrAt1mH9LZExm9mQS7hBlH/ExmoQzEFj3AbIMjRxxkocNsLbokOlx2XID+DAaebDJFXEZ8zKQbBwdf64pKmBjAndMZnHzl+84GHJwvv23V6P1/TJEklh41QdLdjATxaKUbgPP3Uah/7uTh2qo72sA0ZYSf4vnhrL5a0f3j+KG/zxBb5QRSbjbRcP8uPWYm10XiElHz4BTA3BjKXUZSXzJzuMPv7ZrFc5leJq/LMx3kAVLe+5PWfG0WR3gCo8ZFBEvOAGqyYxgA+Sfxbd8yWZwo=
  organization: charon
  space: julekalender-webservice
  on:
    repo: DanielIdris/Julekalender-webservice
