language: java
jdk:
- oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.idris94@gmail.com
  password:
    secure: oJQZQ4lg1q0Y/+MHPXpvP93MHIP7LO+I0TWNxhTrBUeGmTA1Y2WbXNyR4sXhsNuKiJwTwQyYcpXc0zaDRDybG+aSFC+g1wS3Y79fhyYS+t0vZHxoPb2/J+F/gZtIZLkiieITyssg2PggsDx+2azZSdw0UhZQ0dwp0kytcCJYdsozlhbLQK3qCo5EyKHlwQ+KFc8ddcUwk9rX7jAu8QTXL1xry78Pc9KZ+Hhc1Si+H5adH/IjJ6qac9xukyGQ7Hnvt6fKPcXPkMBkjUrrAdFP8EYdU8qvLxxshnRF3dndYcMbiMsXfc3Jl+w114b038sMJIBGPFSlVryAk94CpDSkx9Wk3tCeBV9X6MqNcJOzcqIvchVi1I4dlruuhJ1w8gfM1kZkF6gkRm0jWAIUxXiXgZsVlpkL5eFWP2xqhzbRW/VQHRZOppuxFu9pBNahSsG5GJnRr84vqk9ByD9NtGfiJ9/1/7dSnxMCPVMh0zBF/o6YLLZewYeNNZOereB5Ee6GPKw2VIbO5uHzrpDYnW8O6yF00jrWizvw0+GFzgFz1ldYybFjTVHerLguFweTB3KCVvRjnYVFsXTDDrOrGhycYgf0M2Z7CGOh+t6NsaUUYGo56z4j2JT6bxOu+ezcFsgpcLy2gaNBI6/KYMckktHTZB6V3eEzd2c3W3rGumz5NME=
  organization: charon
  space: julekalender-webservice
  on:
    repo: DanielIdris/Julekalender-webservice
