language: java
jdk:
- oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.idris94@gmail.com
  password:
    secure: ZPE1yHrzUnd6xSWB6fR0IvDyY/gokyWPGernCceQiK5mZAzr9j3DLoDNJwXHU35sOJgtvs1soPYAhVPW6rNVwyWmPucCeu/YMsm0lLcop1ZEboY6vbFHmhRrew25yjwZZrJxIPJA+mkI+d1urWUoE1xtDBYn1qs8QuflU2velJp22pAFgCqa1lJK8mP7nLdhK8iLR0fifpHQzGQo917U3aEDyvzjAPXRDNx6GeZSKi2Tu0/s0++LuI0pcyy3fNl3a2YxAMtD3K0HrzlFXsc9jTV/+Zfwg5oUwksPd4tunsv9PvGSF5wFeV287hjSZYTQohVsOGamjLyae2XWHs5/L2XBrBqGVDE/DtT5uRR/9eFzTLYF9Hcex+7lrvVx16mQiVs4TS9FxuIusuppuxaHjbDHZEJyv9Tv024O0//3/k6XYOx0h4UYdDfZEILEkQjc9SoKe+jLH/wwyPt8HvATik9MJTh8uPMprvp+hV47tyynIPMh6UcS95v3XE6yFhV8BT6oHcQfhCoqshT+4VOZzX64zORhEYFIEBP+Dpl/+1JQmd1PAKdp0YyIeoO0eDpYg9ybvaD3GEDGwCSNmHQXHvCq6Bz8EuCvbkzoSZo5v99vdqxSEAnPopm66QztY188exGQQTai7BPKisgS+fBJahg+TZoRc+37tDFWlttDj2o=
  organization: charon
  space: julekalender-webservice
  on:
    repo: DanielIdris/Julekalender-webservice
